"""Further Reportlab resources

<a href="http://www.reportlab.com/software/opensource/rl-toolkit/">Official
Reportlab site: http://www.reportlab.com/software/opensource/rl-toolkit/</a>

<a href="http://www.reportlab.com/software/opensource/rl-toolkit/api/">API
documentation: http://www.reportlab.com/software/opensource/rl-toolkit/api/</a>

<a href="http://www.reportlab.com/software/opensource/rl-toolkit/guide/">Reportlab user guide:
http://www.reportlab.com/software/opensource/rl-toolkit/guide/</a>

The name Reportlab is a bit of a misnomer. It is really a toolkit for creating
pdfs and does not have tools specifically aimed at generating <i>reports</i> in
the ERP/CRM sense of the word. For the kind of reports that are generated by
programs such as Crystal Reports and Jasper, there is a reporting library built
on top of Reportlab called Geraldo.

<a href="http://www.geraldoreports.org/">Geraldo:
http://www.geraldoreports.org/</a>



"""
